### ISSUE TITLE
The Absolute State of Cutekit

### ISSUE THREAD

**Issue by cutekitaneurysm** [cute-engineering/cutekit#13]
a very long hellish pipeline of osdev has led me to trying to use cutekit as a build system for a kernel i've attempted to develop. this is singlehandedly the worst idea I have ever had. here's why:

i stumble upon this project with semi high expectations as the code looks pretty alright.
i decide "fuck it, why not" and figure i might as well give it a shot. since it's python, I figure I can go install it through pip or something, right?

hell no. the pypi page for cutekit is entirely non-existent! not even there, yet linked for some ungodly reason.
"why would they link it if it doesn't even exist!?" i exclaim, barely stopping myself from sending my fist into my monitor this early.
calm down, they just went through a rebrand, it can't be blamed that hard for this. let's do some digging, see if we can find anything more useful.
i open the setup.py in desperation, and- oh! a contact email and a webpage. let's check this out, see what i can fi-

_An error occurred during a connection to cute.engineering._

IT'S NOT EVEN A REAL WEBPAGE!! WHAT THE _**FUCK**_ IS THIS?
THERE IS A WEBPAGE URL, THAT WOULD BE DISPLAYED ON THE PYPI IF IT ACTUALLY **EXISTED**, BUT IT FUCKING **DOESN'T**, SO WHO **GIVES A SHIT.**

okay, okay, i'll be alright. let me look a bit deeper, find some pre-rebrand stuff maybe.
taking about 5 minutes of effort, i figured out it used to be called `osdk`. now we're getting somewhere.

holy shit, it actually has a pypi! THAT ISN'T EVEN ON THE LATEST VERSION.
THERE IS NO PYPI EXISTANT FOR THE REBRAND AND NO UPDATE AFTER 2 WEEKS. WHAT. **THE.** _**FUCK.**_

"_**WHO IS RUNNING THIS SHIT?**_" i ask, currently on my last nerve with this project. there's a homepage linked, seems to work this t- what?
it's a osdev wiki? tutorial? thing? **ENTIRELY IN FRENCH.**

_**WHY ARE YOU LINKING TO A WIKI, LET ALONE A SINGLE LANGUAGE WIKI, IN AN OPEN SOURCE BUILD SYSTEM. I AM GOING TO CRY.**_

i finally pull myself out of the organizational woes of this project and decide "ugh, fine. i'll just install it from source."
THE SETUP.PY DOES NOT FUNCTION.
```
cutekit % pip3 install .
[irrelevant backtrace snip]
        File "/home/[snip]/temp/cutekit/cutekit/cmds.py", line 3, in <module>
          import requests
      ModuleNotFoundError: No module named 'requests'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
cutekit %
```

I very much have requests.

```
cutekit % python3
Python 3.11.4 (main, Jun  8 2023, 02:02:15) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> import sys
>>> 'requests' in sys.modules
True
>>> quit()
cutekit % xbps-query -s "requests"
[*] c-ares-1.19.1_1           Library for asynchronous DNS requests
[*] python3-requests-2.31.0_1 Python3 HTTP library for human beings
```

**YOU CANNOT**

## THE FUCKING
# PROGRAM
# IT DOES NOT WORK, UNDER ANY CIRCUMSTANCE. WHAT IN THE UNGODLY FRESH FUCK.

this is a MASTERCLASS on how to completely and utterly fuck up an open source project. this is literally somehow the worst condition i have EVER seen a project in! i WEEP for any poor soul aside from the developers who decided against their own better judgement to use this for their project.

how does it even get like this? what series of unfortunate, terrible, no good, bad bad decisions leads to something like this? what unloving god would send such a project down to us?

i don't know, i don't want to know, and by whatever powers that be

i hope i never have to know.

**Comment by keyboard-slayer** [comment]
Ok boomer

**Comment by cutekitaneurysm** [comment]
![image](https://github.com/cute-engineering/cutekit/assets/141356377/b45bf2bc-123f-4157-9791-b2ca20485452)
your sins will not be forgotten

**Comment by sleepy-monax** [comment]
skill issue

**Comment by keyboard-slayer** [comment]
Ok boomer

Le jeu. 3 août 2023 à 20:56, cutekitaneurysm ***@***.***> a
écrit :
